# BSPWM
[managers.packages]
items = [
  "bspwm", "sxhkd",
  "polybar", "picom",
  "feh", "rofi", "python-pywal",
  "gtk-engines", "gtk-engine-murrine",
  "gtk3", "gtk4", "xdg-desktop-portal", "xdg-desktop-portal-gtk",
]
