[managers.packages]
items = [
  "wget", "curl", "git",
  "p7zip", "zip", "unzip",
  "clang", "gcc",
  "gvfs", "gvfs-afc","gvfs-gphoto2", 
  "gvfs-mtp","gvfs-nfs","gvfs-smb",
  "fzf", "ripgrep", "fd","eza",
  "xsel", "xclip", "xdotool",
  "os-prober", "timeshift",
  "gnome-screenshot", "imagemagick",
  "htop","btop",
  "gufw","xdg-utils",
  "gum", "yad", "bat",
  "stow", "luarocks",

  # GTK settings editor, for Wayland : https://github.com/nwg-piotr/nwg-look
  "nwg-look",
  # Generate/Export Material You Color Palette: https://github.com/InioX/matugen
  "matugen-bin",
  # Generate and change color-schemes on the fly.: https://github.com/dylanaraps/pywal
  "python-pywal",
]

[managers.serv_start]
items = [
  "ufw"
]
