# Fonts from normal arch repos
[managers.packages]
items = [
  "ttf-sourcecodepro-nerd",
  "ttf-jetbrains-mono-nerd",
]

# Fonts using fontsdl; custom script to download google fonts
[managers.fontsdl]
items = [
  "https://fonts.googleapis.com/css2?family=B612:ital,wght@0,400;0,700;1,400;1,700&display=swap",
  # "https://fonts.googleapis.com/css2?family=Rampart+One&display=swap"
]

