# Login Managers
[managers.system]
items = [

  # "sddm",
  # "qt5-svg",
  # "qt5-graphicaleffects",
  # "qt5-quickcontrols2",
  # "sddm-sugar-dark",

  # "lightdm",
  # "lightdm-gtk-greeter",
  # "lightdm-webkit2-greeter",
  # "lightdm-webkit2-theme-glorious",

  "ly",
]

[managers.serv_enable]
items = [
  # "sddm",
  # "lightdm",
  "ly",
]
