# Themeing 
[managers.packages]
items = [
  # icons
  # "whitesur-icon-theme", # https://github.com/vinceliuice/WhiteSur-icon-theme
  "mcmojave-circle-icon-theme-git", # https://github.com/vinceliuice/McMojave-circle
  # "tela-circle-icon-theme-all", # https://github.com/vinceliuice/Tela-circle-icon-theme

  # themes
  # "orchis-theme-git", # https://github.com/vinceliuice/Orchis-theme
  "mojave-gtk-theme-git", # https://github.com/vinceliuice/Mojave-gtk-theme
  # "whitesur-gtk-theme", # https://github.com/vinceliuice/WhiteSur-gtk-theme
]
