# --------------------------- #
#    Work Related Packages    #
# --------------------------- #

[managers.packages]
items = [
  "go",                  # Golang
  "sqlit",               # A user friendly TUI for SQL databases.
  "github-cli",          # Github cli
  "migrate",             # Migrate package for database migration with sql files
  "fnm",                 # Fast and simple node version manaager
  "serpl",               # Search and Replace through terminal
  "docker",              # Containerization platform
  "docker-compose",      # Tool for defining and running multi-container Docker apps
  "gpu-screen-recorder", # Screen Recording 
  "slurp",               # Region Selection: for region recording
  "qutebrowser",         # Keyboard driven minial sleep browser
  "docker-buildx",       # Buildx plugin for docker 
  "luajit-tiktoken-bin", # binding of rust tiktoken to lua
  "markdown-oxide",      # Markdown-Oxide is a Personal Knowledge Management System
  "presenterm",          # presenterm lets you create presentations in markdown format and run them from your terminal
  "mermaid-cli",         # required by presenterm to show mermaid diagrams
]

[managers.cargo]
items = [
  "wiki-tui", # A simple and easy to use Wikipedia Text User Interface
]


[managers.serv_start]
items = [
  "docker", # Start Docker daemon at login
]
