# X11 Display Server Packages
[managers.packages]
items = [
  "xorg-xhost",
  "xorg-server",
  "xorg-xinit",
  "xorg-xsetroot",
  "xorg-xkill",
  "xorg-xwininfo",
  "xorg-xprop",
  "xorg-xrandr",
  "xorg-xbacklight",
  "xorg-xinput",
]
