# X11 Display Server Packages
[managers.packages]
items = [
  "xorg-xhost",      # X server access control utility
  "xorg-server",     # Core Xorg server
  "xorg-xinit",      # Start X server manually
  "xorg-xsetroot",   # Change X root window properties (background, color)
  "xorg-xkill",      # Kill unresponsive X applications
  "xorg-xwininfo",   # Display window information
  "xorg-xprop",      # Display/set window properties
  "xorg-xrandr",     # Configure screen resolution and rotation
  "xorg-xbacklight", # Adjust screen backlight brightness
  "xorg-xinput",     # Configure/input device settings
]
