[colors.primary]
background = '#151218'
foreground = '#e7e0e8'
 
[colors.cursor]
text = '#e7e0e8'
cursor = '#ccc4cf' 
 
[colors.vi_mode_cursor]
text = '#151218'
cursor = '#d7bafb' 
 
[colors.search.matches]
foreground = '#4a454e' 
background = '#f2b7c1' 
 
[colors.search.focused_match]
foreground = '#4a454e' 
background = '#d7bafb' 
 
[colors.footer_bar]
foreground = '#4a454e' 
background = '#e7e0e8' 
 
[colors.hints.start]
foreground = '#4a454e' 
background = '#cfc2da' 
 
[colors.hints.end]
foreground = '#4a454e' 
background = '#cfc2da' 
 
[colors.selection]
text = '#151218'
background = '#d7bafb'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#d7bafb' 
yellow = '#6c538c' 
blue = '#d7bafb' 
magenta = '#f2b7c1' 
cyan = '#cfc2da' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
