[colors.primary]
background = '#0f1417'
foreground = '#dfe3e7'
 
[colors.cursor]
text = '#dfe3e7'
cursor = '#c0c8cd' 
 
[colors.vi_mode_cursor]
text = '#0f1417'
cursor = '#8bd0ef' 
 
[colors.search.matches]
foreground = '#40484c' 
background = '#c6c2ea' 
 
[colors.search.focused_match]
foreground = '#40484c' 
background = '#8bd0ef' 
 
[colors.footer_bar]
foreground = '#40484c' 
background = '#dfe3e7' 
 
[colors.hints.start]
foreground = '#40484c' 
background = '#b4cad6' 
 
[colors.hints.end]
foreground = '#40484c' 
background = '#b4cad6' 
 
[colors.selection]
text = '#0f1417'
background = '#8bd0ef'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#8bd0ef' 
yellow = '#116682' 
blue = '#8bd0ef' 
magenta = '#c6c2ea' 
cyan = '#b4cad6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
