[colors.primary]
background = '#121318'
foreground = '#e3e1e9'
 
[colors.cursor]
text = '#e3e1e9'
cursor = '#c6c5d0' 
 
[colors.vi_mode_cursor]
text = '#121318'
cursor = '#bac3ff' 
 
[colors.search.matches]
foreground = '#46464f' 
background = '#e5bad8' 
 
[colors.search.focused_match]
foreground = '#46464f' 
background = '#bac3ff' 
 
[colors.footer_bar]
foreground = '#46464f' 
background = '#e3e1e9' 
 
[colors.hints.start]
foreground = '#46464f' 
background = '#c3c5dd' 
 
[colors.hints.end]
foreground = '#46464f' 
background = '#c3c5dd' 
 
[colors.selection]
text = '#121318'
background = '#bac3ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bac3ff' 
yellow = '#515b92' 
blue = '#bac3ff' 
magenta = '#e5bad8' 
cyan = '#c3c5dd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
