[colors.primary]
background = '#0d1418'
foreground = '#dce3e9'
 
[colors.cursor]
text = '#dce3e9'
cursor = '#bbc8d2' 
 
[colors.vi_mode_cursor]
text = '#0d1418'
cursor = '#ddc663' 
 
[colors.search.matches]
foreground = '#3c4850' 
background = '#97ceec' 
 
[colors.search.focused_match]
foreground = '#3c4850' 
background = '#ddc663' 
 
[colors.footer_bar]
foreground = '#3c4850' 
background = '#dce3e9' 
 
[colors.hints.start]
foreground = '#3c4850' 
background = '#d3bfe6' 
 
[colors.hints.end]
foreground = '#3c4850' 
background = '#d3bfe6' 
 
[colors.selection]
text = '#0d1418'
background = '#ddc663'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ddc663' 
yellow = '#6f5d00' 
blue = '#ddc663' 
magenta = '#97ceec' 
cyan = '#d3bfe6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
