#!/bin/sh

## Author : Ankur Kumar (SirJager)
## Github : @SirJager

# -a, --add (<class_name>|*)[:(<instance_name>|*)[:(<name>|*)]]
# [-o|--one-shot] [monitor=MONITOR_SEL|desktop=DESKTOP_SEL|node=NODE_SEL] [state=STATE] [layer=LAYER]
# [split_dir=DIR] [split_ratio=RATIO]
# [(hidden|sticky|private|locked|marked|center|follow|manage|focus|border)=(on|off)] [rectangle=WxH+X+Y]

bspc rule -a '*' -o \
	state=floating \
	focus=on \
	follow=on \
	border=on \
	center=on &&
	"$@"
