#!/bin/sh

## Author : Ankur Kumar (SirJager)
## Github : @SirJager
if toggle polybar; then
  polybar-msg cmd hide
  sleep 0.4
  bspc config window_gap 0
  bspc config top_padding 0
  bspc config bottom_padding 0
  bspc config right_padding 0
  bspc config left_padding 0
  bspc config border_width 0
else
  bspc config window_gap 15 &     # 5
  bspc config top_padding 36 &    # 35 25* 45 for polybar
  bspc config bottom_padding 15 & # 6
  bspc config right_padding 15 &  # 5
  bspc config left_padding 15 &   # 5
  bspc config border_width 2 &
  sleep 0.4
  polybar-msg cmd show
fi
