#!/bin/sh

## Author : Ankur Kumar (SirJager)
## Github : @SirJager
if toggle polybar; then
  polybar-msg cmd hide
  sleep 0.4
  bspc config window_gap 0
  bspc config top_padding 0
  bspc config bottom_padding 0
  bspc config right_padding 0
  bspc config left_padding 0
  bspc config border_width 0
else
  bspc config window_gap 20 &
  bspc config top_padding 36 &
  bspc config bottom_padding 20 &
  bspc config left_padding 20 &
  bspc config right_padding 20 &
  bspc config border_width 3 &
  sleep 0.4
  polybar-msg cmd show
fi
