require "user.plugins.configs.alpha"
require "user.plugins.configs.nvim-web-devicons"
require "user.plugins.configs.noice"
require "user.plugins.configs.bufferline"
require "user.plugins.configs.neoscroll"
require "user.plugins.configs.telescope"
require "user.plugins.configs.illuminate"
require "user.plugins.configs.nvim-surround"
require "user.plugins.configs.whichkey"
require "user.plugins.configs.windline"
require "user.plugins.configs.colorizer"
require "user.plugins.configs.comments"
require "user.plugins.configs.flash"
require "user.plugins.configs.gitsigns"
require "user.plugins.configs.harpoon"
require "user.plugins.configs.lsp"
require "user.plugins.configs.markdown-preview"
require "user.plugins.configs.rest-nvim"
require "user.plugins.configs.symbols-outline"
require "user.plugins.configs.todo-comments"
require "user.plugins.configs.toggleterm"
require "user.plugins.configs.zen-mode"
require "user.plugins.configs.neorg"
-- require "user.plugins.configs.luasnip"
require "user.plugins.configs.color-picker"
require "user.plugins.configs.neo-tree"
-- require "user.plugins.configs.nvim-tree"
require "user.plugins.configs.ufo"
require "user.plugins.configs.extras.codeium"
require "user.plugins.configs.extras.lab"
require "user.plugins.configs.extras.nx"
require "user.plugins.configs.extras.live-server"

