require "user.plugins.configs.lsp.mason"
require "user.plugins.configs.lsp.lspsaga"
require "user.plugins.configs.lsp.lspconfig"
require "user.plugins.configs.lsp.prettier"
require "user.plugins.configs.lsp.none-ls"
require "user.plugins.configs.lsp.dap"
require "user.plugins.configs.lsp.neodev"
require "user.plugins.configs.lsp.cmp"
require "user.plugins.configs.lsp.nvim-autopairs"
require "user.plugins.configs.lsp.nvim-ts-autotag"
require "user.plugins.configs.lsp.nvim-lint"
require "user.plugins.configs.lsp.tailwindcss-colorizer-cmp"
require "user.plugins.configs.lsp.nvim-treesitter"
require "user.plugins.configs.lsp.nvim-treesitter-context"
-- require "user.plugins.configs.lsp.go"
