foreground         #EEF1EB
background         #110E14
cursor             #BBCEAF 

active_tab_foreground     #110E14
active_tab_background     #BC7195
inactive_tab_foreground   #BC7195
inactive_tab_background   #110E14

active_border_color   #443150
inactive_border_color #BC7195
bell_border_color     #592F4B

    # Commands
color2       #EEF1EB
 
    # Prompt
color7       #BC7195
color4       #8A4A52
color0       #438E6A

    # Color Overrides
# color1       #BBCEAF
# color3       #4F314B
# color5       #5E464D
# color6       #734952
# color8       #463346
# color9       #443150
# color10      #8A4A52
# color11      #4F314B
# color12      #4C4145
# color13      #5E464D
# color14      #734952
# color15      #BC7195
