foreground         #D5E7C4
background         #2A183B
cursor             #91A46B 

active_tab_foreground     #2A183B
active_tab_background     #BF91B3
inactive_tab_foreground   #BF91B3
inactive_tab_background   #2A183B

active_border_color   #6E5B94
inactive_border_color #BF91B3
bell_border_color     #5D3C6C

    # Commands
color2       #D5E7C4
 
    # Prompt
color7       #BF91B3
color4       #8A6371
color0       #406E4C

    # Color Overrides
# color1       #91A46B
# color3       #4E3A5B
# color5       #63545D
# color6       #765C68
# color8       #41384A
# color9       #6E5B94
# color10      #8A6371
# color11      #4E3A5B
# color12      #524B50
# color13      #63545D
# color14      #765C68
# color15      #BF91B3
