return {
  ensure_installed = {
    "bash-language-server",
    "clangd",
    "clang-format",
    "css-lsp",
    "deno",
    "emmet-language-server",
    "html-lsp",
    "json-lsp",
    "luacheck",
    "markdownlint",
    "marksman",
    "stylua",
    "prismals",
    "prettierd",
    "shellcheck",
    "shfmt",
    "lua-language-server",
    "unocss-language-server",
    "typescript-language-server",
    "tailwindcss-language-server",
  },
}
