#!/bin/bash

file_path=""
orig_dir="$PWD"
file_path=$(rg --files --hidden --glob '!{.git,node_modules}/*' | fzf \
	--preview "bat --style=numbers --color=always --line-range :100 {}" \
	--height 40% --layout=reverse --border) || exit 0
[ -z "$file_path" ] && exit 0
file_path=$(realpath "$file_path")
cd "$(dirname "$file_path")" && $EDITOR "$file_path" && cd "$orig_dir"
