#!/bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d ⼀ ⼆ 三 四 五 六 七 ⼋ ⼏ ⼗
# bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xset r rate 200 50
xsetroot -cursor_name left_ptr

bspc config automatic_scheme alternate &
bspc config initial_polarity second_child &
bspc config focus_follows_pointer false &

bspc config normal_border_color "#00000000"
bspc config focused_border_color "#00000000"

WALLPAPER_PATH="/mnt/storage/wallpaper/gruvbox/wolf.jpg"
if [ -f ~/.cache/current_wallpaper ]; then
  LAST_WALLPAPER=$(cat ~/.cache/current_wallpaper) # Get the last/current wallpaper path
  if [ -f "$LAST_WALLPAPER" ]; then                # Check if the current wallpaper exists
    WALLPAPER_PATH="$LAST_WALLPAPER"
  fi
fi
[ -f ~/.local/bin/wallpaper ] && ~/.local/bin/wallpaper -tmux -dunst -bspwm -polybar -path="$WALLPAPER_PATH" &

# windows:padding
bspc config window_gap 20 &
bspc config top_padding 36 &
bspc config bottom_padding 20 &
bspc config left_padding 20 &
bspc config right_padding 20 &
bspc config border_width 3 &

bspc config split_ratio 0.58 &
bspc config click_to_focus true &
bspc config borderless_monocle true &
bspc config gapless_monocle true &

bspc rule -a mpv state=fullscreen focus=on border=off &
bspc rule -a Yad state=floating &
bspc rule -a kitty state=floating focus=on &
bspc rule -a scrcpy state=floating &
bspc rule -a polkit-gnome-authentication-agent-1 border=off state=floating &
bspc rule -a fcitx-config-gtk3 border=off state=floating &
bspc rule -a kdeconnect-indicator border=off state=floating &
bspc rule -a FLTK border=off state=floating &              # weylus
bspc rule -a "blueman-manager" border=off state=floating & # blueman
bspc rule -a "blueman-applet" border=off state=floating &  # blueman
bspc rule -a lutris desktop='^10' focus=on &
bspc rule -a heroic desktop='^10' focus=on &
bspc rule -a steam desktop='^10' focus=on &
bspc rule -a "qemu-system-x86_64" state=floating &

# append this to /etc/sudoers: jager ALL=NOPASSWD:/usr/bin/chmod
sudo chmod a+rw /sys/class/backlight/amdgpu_bl2/brightness &

# Picom: sudo pacman -S picom
command -v picom >/dev/null 2>&1 && picom &

# Authentication: Polkit Gnone : sudo pacman -S polkit-gnome
[ -f "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1" ] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dunst: sudo pacman -S dunst
command -v dunst >/dev/null 2>&1 && dunst &

# Polybar: sudo pacman -S polybar
[ -f ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

# Network Manager Applet: sudo pacman -S nm-applet
command -v nm-applet >/dev/null 2>&1 && nm-applet --indicator &

# Bluetooth Manager Applet: sudo pacman -S blueman bluez bluez-utils
command -v blueman-applet >/dev/null 2>&1 && blueman-applet &

# Low Batter Script:
[ -f ~/.config/sxhkd/scripts/lowbattery ] && ~/.config/sxhkd/scripts/lowbattery &
