#!/bin/bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc |
  column -t -s $'\t' |
  rofi -dmenu -p "Search keybind" \
  -theme "$HOME/.config/sxhkd/rofi/vertical.rasi" \
  -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40
