general {
    col.active_border = rgba(BC7195ff) rgba(110E14ff) 45deg
    col.inactive_border = rgba(4C4145ff) rgba(8A4A52ff) 45deg
}

group {
    col.border_active = rgba(4C4145ff) rgba(8A4A52ff) 45deg
    col.border_inactive = rgba(0F0E10cc) rgba(160D14cc) 45deg
    col.border_locked_active = rgba(5E464Dff) rgba(734952ff) 45deg
    col.border_locked_inactive = rgba(110E12cc) rgba(130E13cc) 45deg
}
