
#█░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
#█▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█


# Set your personal hyprland configuration here
# for sample file, please refer https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

$term = kitty bash -c tmux attach
$editor = code --ozone-platform-hint=wayland --disable-gpu --password-store=gnome
$file = dolphin
$browser = chromium

# Window/Session actions
bind = $mainMod, w, exec, $scrPath/dontkillsteam.sh # killactive, kill the window on focus
bind = $mainMod, f, togglefloating, # toggle the window on focus to float
bind = $mainMod, G, togglegroup, # toggle the window on focus to group (tab mode)
bind = $mainMod, L, exec, swaylock # lock screen
bind = $mainMod SHIFT, F, exec, $scrPath/windowpin.sh # toggle pin on focused window
bind = $CONTROL, ESCAPE, exec, killall waybar || waybar # toggle waybar


# Application shortcuts
bind = ALT, return, exec, $term   # open terminal
bind = $mainMod, E, exec, $file # open file manager
bind = $mainMod, v, exec, $editor # open vscode
bind = $mainMod, B, exec, $browser # open browser
bind = $CONTROL SHIFT, ESCAPE, exec, $scrPath/sysmonlaunch.sh  # open htop/btop if installed or default to top (system monitor)


# Rofi is toggled on/off if you repeat the key presses
bind = ALT, space, exec, pkill -x rofi || $scrPath/rofilaunch.sh d # launch desktop applications
bind = $mainMod, tab, exec, pkill -x rofi || $scrPath/rofilaunch.sh w # switch between desktop applications
bind = $mainMod, R, exec, pkill -x rofi || $scrPath/rofilaunch.sh f # browse system files

# Special workspaces (scratchpad)
bind = $mainMod SHIFT, S, movetoworkspacesilent, special
bind = $mainMod, S, togglespecialworkspace,









