
[urgency_low]
    background = "#0F0E10"
    foreground = "#EEF1EB"
    frame_color = "#160D14"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 4

[urgency_normal]
    background = "#592F4B"
    foreground = "#EEF1EB"
    frame_color = "#8A4A52"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 4
