
[urgency_low]
    background = "#271F2A"
    foreground = "#D5E7C4"
    frame_color = "#431438"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 4

[urgency_normal]
    background = "#5D3C6C"
    foreground = "#D5E7C4"
    frame_color = "#8A6371"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 4
