# : Manager [[[

[manager]
cwd = { fg = "#dfe3e7" }

# Tab
tab_active = { fg = "#003546", bg = "#8bd0ef", bold = true }
tab_inactive = { fg = "#bde9ff", bg = "#001f2a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#8a79ff", bg = "#8a79ff" }
marker_cut = { fg = "#e3dfff", bg = "#e3dfff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c6c2ea", bg = "#c6c2ea" }

# Count
count_copied = { fg = "#191836", bg = "#e3dfff" }
count_cut = { fg = "#191836", bg = "#e3dfff" }
count_selected = { fg = "#003546", bg = "#c6c2ea" }

# Border
border_symbol = "│"
border_style  = { fg = "#8bd0ef" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#003546", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#8bd0ef", fg = "#003546", bold = true }
normal_alt  = { bg = "#40484c", fg = "#c0c8cd" }

# Select mode
select_main = { bg = "#b4cad6", fg = "#1f333c", bold = true }
select_alt  = { bg = "#40484c", fg = "#c0c8cd" }

# Unset mode
unset_main = { bg = "#c6c2ea", fg = "#2e2d4d", bold = true }
unset_alt  = { bg = "#40484c", fg = "#c0c8cd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8bd0ef", bg = "#353a3d" }
progress_error = { fg = "#ffb4ab", bg = "#353a3d" }

# Permissions
permissions_t = { fg = "#55839c" }
permissions_w = { fg = "#5c50c3" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#5d46ff" }
permissions_s = { fg = "#24b6ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8bd0ef" }
active = { fg = "#c6c2ea", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#8bd0ef" }
value = { fg = "#dfe3e7" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8bd0ef", bg = "#003546" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8bd0ef" }
title = {}
hovered = { fg = "#e3dfff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a3d" }
cand = { fg = "#8bd0ef" }
rest = { fg = "#003546" }
desc = { fg = "#dfe3e7" }
separator = " ▶ "
separator_style = { fg = "#dfe3e7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe3e7" }
run = { fg = "#dfe3e7" }
footer = { fg = "#1f333c", bg = "#b4cad6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c6c2ea" }
title_warn = { fg = "#8bd0ef" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dfe3e7" },
    { name = "*/", fg = "#8bd0ef" },
]

# : ]]]
