# : Manager [[[

[manager]
cwd = { fg = "#dce3e9" }

# Tab
tab_active = { fg = "#3a3000", bg = "#ddc663", bold = true }
tab_inactive = { fg = "#fbe27c", bg = "#221b00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5cc2ff", bg = "#5cc2ff" }
marker_cut = { fg = "#c2e8ff", bg = "#c2e8ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#97ceec", bg = "#97ceec" }

# Count
count_copied = { fg = "#001e2c", bg = "#c2e8ff" }
count_cut = { fg = "#001e2c", bg = "#c2e8ff" }
count_selected = { fg = "#3a3000", bg = "#97ceec" }

# Border
border_symbol = "│"
border_style  = { fg = "#ddc663" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#3a3000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ddc663", fg = "#3a3000", bold = true }
normal_alt  = { bg = "#3c4850", fg = "#bbc8d2" }

# Select mode
select_main = { bg = "#d3bfe6", fg = "#382a49", bold = true }
select_alt  = { bg = "#3c4850", fg = "#bbc8d2" }

# Unset mode
unset_main = { bg = "#97ceec", fg = "#003548", bold = true }
unset_alt  = { bg = "#3c4850", fg = "#bbc8d2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ddc663", bg = "#333a3f" }
progress_error = { fg = "#ffb4ab", bg = "#333a3f" }

# Permissions
permissions_t = { fg = "#8751bb" }
permissions_w = { fg = "#248dc6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#29aeff" }
permissions_s = { fg = "#d7ae07" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ddc663" }
active = { fg = "#97ceec", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ddc663" }
value = { fg = "#dce3e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ddc663", bg = "#3a3000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ddc663" }
title = {}
hovered = { fg = "#c2e8ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#333a3f" }
cand = { fg = "#ddc663" }
rest = { fg = "#3a3000" }
desc = { fg = "#dce3e9" }
separator = " ▶ "
separator_style = { fg = "#dce3e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dce3e9" }
run = { fg = "#dce3e9" }
footer = { fg = "#382a49", bg = "#d3bfe6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#97ceec" }
title_warn = { fg = "#ddc663" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dce3e9" },
    { name = "*/", fg = "#ddc663" },
]

# : ]]]
