# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "sudo pacman --needed -S #:?"
remove = "sudo pacman -Rns #:?"

plural_name = "initial packages (install everything that Rebos needs)"

hook_name = "init_pkgs"


# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = true
arg_sep = " "
