# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "yay --answerdiff None --answerclean None --needed -S #:?"

# this command does not throws erros if package is not present.
remove = "yay -Rns $(yay -Qq #:? 2>/dev/null)"

plural_name = "system packages"

hook_name = "system_packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = true
arg_sep = " "
