# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "yay --needed -S #:?"
remove = "yay -Rns #:?"

plural_name = "system packages"

hook_name = "system_packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = true
arg_sep = " "
