# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "uv tool install #:?"
remove = "uv tool uninstall #:?"

plural_name = "python packages"

hook_name = "python_packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = false
