# ----------------------- #
#    Symlinks Builder     #
# ----------------------- #

add = "~/.config/rebos/scripts/symbuilder --link --sudo #:?"
remove = "~/.config/rebos/scripts/symbuilder --unlink --sudo #:?"

plural_name = "symlinks builder"

hook_name = "symbuilder"

[config]
many_args = false
