# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "paru --fm nvim --needed -S #:?"
remove = "paru -Rns #:?"

plural_name = "system packages"

hook_name = "system_packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = true
